version: 1
last_updated: "2026-02-25"
north_star: >-
  Enterprise Document Processing + RAG Engine: upload document, transform into
  chunked and indexed knowledge, and answer queries with mandatory citations.

project:
  id: secure-electron-474908-k9
  number: "994021588311"
  region: europe-west4
  zone: europe-west4-a
  environment_tag: Production

invariants:
  - single_source_of_truth_spec
  - stable_contracts_pubsub_http_sql
  - idempotent_reprocessing_by_doc_id_and_hash
  - rag_answers_must_include_citations
  - traceability_with_trace_id_and_job_id

storage:
  existing:
    run_sources:
      name: run-sources-secure-electron-474908-k9-us-central1
      location: US-CENTRAL1
      uniform_bucket_level_access: true
      public_access_prevention: inherited
      cmek_enabled: false
    raw_bucket:
      name: alchimista-raw-994021588311
      location: EUROPE-WEST4
      uniform_bucket_level_access: true
      public_access_prevention: enforced
      cmek_key: projects/secure-electron-474908-k9/locations/europe-west4/keyRings/alchimista-data-kr/cryptoKeys/alchimista-data-key
    processed_bucket:
      name: alchimista-processed-994021588311
      location: EUROPE-WEST4
      uniform_bucket_level_access: true
      public_access_prevention: enforced
      cmek_key: projects/secure-electron-474908-k9/locations/europe-west4/keyRings/alchimista-data-kr/cryptoKeys/alchimista-data-key
    reports_bucket:
      name: alchimista-reports-994021588311
      location: EUROPE-WEST4
      uniform_bucket_level_access: true
      public_access_prevention: enforced
      cmek_key: projects/secure-electron-474908-k9/locations/europe-west4/keyRings/alchimista-data-kr/cryptoKeys/alchimista-data-key
  target:
    raw_bucket:
      name: alchimista-raw-994021588311
      required_prefix: raw/
      cmek_required: true
      ubla_required: true
      status: ready
    processed_bucket:
      name: alchimista-processed-994021588311
      required_prefix: processed/
      cmek_required: true
      ubla_required: true
      status: ready
    reports_bucket:
      name: alchimista-reports-994021588311
      required_prefix: reports/
      cmek_required: true
      ubla_required: true
      status: ready

pubsub:
  ingest_topic:
    name: doc-ingest-topic
    full_name: projects/secure-electron-474908-k9/topics/doc-ingest-topic
    exists: true
  ingest_subscription:
    name: doc-ingest-sub
    full_name: projects/secure-electron-474908-k9/subscriptions/doc-ingest-sub
    exists: true
  dead_letter_topic:
    name: doc-ingest-topic-dlq
    full_name: projects/secure-electron-474908-k9/topics/doc-ingest-topic-dlq
    exists: true
  dead_letter_subscription:
    name: doc-ingest-topic-dlq-sub
    full_name: projects/secure-electron-474908-k9/subscriptions/doc-ingest-topic-dlq-sub
    exists: true

kms:
  key_ring: projects/secure-electron-474908-k9/locations/europe-west4/keyRings/alchimista-data-kr
  crypto_key: projects/secure-electron-474908-k9/locations/europe-west4/keyRings/alchimista-data-kr/cryptoKeys/alchimista-data-key
  rotation_period: 2592000s
  next_rotation_time: "2026-03-27T10:36:09.094029Z"

sql:
  instance: alchimista-test-db
  connection_name: secure-electron-474908-k9:europe-west4:alchimista-test-db
  database: postgres
  private_network: projects/secure-electron-474908-k9/global/networks/alchimista-vpc
  backup_enabled: true
  pitr_enabled: true
  deletion_protection_enabled: true
  app_db_secret: alchimista-db-url
  app_db_secret_exists: true

vector_search:
  provider: vertex_ai_vector_search
  index_id: "3994068346873053184"
  endpoint_id: "5596857233007706112"
  deployed_index_id: "alchimista_chunks_deployed_v3"
  index_display_name: alchimista-doc-chunks-v2
  endpoint_display_name: alchimista-doc-chunks-endpoint-v2
  deployment_status: deployed
  deploy_operations:
    - "8784978471479672832" # v1 endpoint deploy attempt
    - "4094197984596590592" # v1 endpoint deploy retry
    - "3211492457631973376" # v2 endpoint deploy attempt
  dimensions: 128
  distance_measure_type: DOT_PRODUCT_DISTANCE
  fallback_provider: sql_embedding_scan

runtime_services:
  ingestion_api_service:
    target_name: ingestion-api-service
    deployed_url: https://ingestion-api-service-pe7qslbcvq-ez.a.run.app
    latest_ready_revision: ingestion-api-service-00012-bfk
    expected_endpoints:
      - POST /v1/ingest
      - POST /v1/ingest/complete
      - POST /v1/connectors/gcs/import
      - POST /v1/admin/replay-dlq
      - POST /v1/admin/retention-policies
      - GET /v1/admin/retention-policies
      - POST /v1/admin/legal-holds
      - POST /v1/admin/legal-holds/release
      - GET /v1/admin/legal-holds
      - POST /v1/admin/retention/enforce
      - POST /v1/decisions
      - POST /v1/decisions/query
      - POST /v1/decisions/export
      - POST /v1/decisions/bundle
      - POST /v1/decisions/package
      - POST /v1/decisions/verify
      - POST /v1/admin/decisions/query
      - GET /v1/decisions/{id}/report
      - GET /v1/doc/{id}
      - GET /v1/healthz
      - GET /v1/readyz
  document_processor_service:
    target_name: document-processor-service
    deployed_url: https://document-processor-service-pe7qslbcvq-ez.a.run.app
    latest_ready_revision: document-processor-service-00014-cqb
    expected_endpoints:
      - POST /v1/process
      - POST /v1/process/pubsub
      - GET /v1/healthz
      - GET /v1/readyz
  rag_query_service:
    target_name: rag-query-service
    deployed_url: https://rag-query-service-pe7qslbcvq-ez.a.run.app
    latest_ready_revision: rag-query-service-00012-m5f
    expected_endpoints:
      - POST /v1/query
      - GET /v1/healthz
      - GET /v1/readyz

service_accounts:
  current_runtime_default: 994021588311-compute@developer.gserviceaccount.com
  target_dedicated:
    ingestion_api_service: ingestion-api-sa@secure-electron-474908-k9.iam.gserviceaccount.com
    document_processor_service: document-processor-sa@secure-electron-474908-k9.iam.gserviceaccount.com
    rag_query_service: rag-query-sa@secure-electron-474908-k9.iam.gserviceaccount.com
  least_privilege_target_roles:
    ingestion_api_service:
      - roles/storage.objectAdmin
      - roles/storage.objectViewer
      - roles/storage.bucketViewer
      - roles/pubsub.publisher
      - roles/pubsub.subscriber (doc-ingest-topic-dlq-sub for replay)
      - roles/cloudsql.client
      - roles/secretmanager.secretAccessor
      - roles/iam.serviceAccountTokenCreator (self-binding for signed URLs)
    document_processor_service:
      - roles/storage.objectViewer
      - roles/storage.objectAdmin
      - roles/storage.bucketViewer
      - roles/pubsub.publisher
      - roles/cloudsql.client
      - roles/secretmanager.secretAccessor
    rag_query_service:
      - roles/cloudsql.client
      - roles/secretmanager.secretAccessor

contracts:
  pubsub_ingest_message:
    required_json: |
      {
        "id": "doc_id",
        "uri": "gs://bucket/raw/doc.pdf",
        "type": "application/pdf",
        "size": 123,
        "tenant": "default",
        "ts": "ISO8601",
        "trace_id": "uuid"
      }
  sql_job_status:
    statuses:
      - QUEUED
      - RUNNING
      - SUCCEEDED
      - FAILED
  query_response:
    required_json: |
      {
        "answers": [
          {
            "text": "...",
            "score": 0.87,
            "citations": [
              {"doc_id": "...", "chunk_id": "..."}
            ]
          }
        ]
      }
  ai_decision_ingest_request:
    required_json: |
      {
        "decision_id": "d-001",
        "model": "gpt-4",
        "model_version": "2024-01",
        "input": "...",
        "output": "approved",
        "confidence": 0.94,
        "context_docs": ["doc_id_1", "doc_id_2"],
        "tenant": "vendor-x",
        "trace_id": "uuid"
      }

benchmark:
  p3_1_baseline:
    name: alchimista_p3_1_baseline_v1
    dataset_path: benchmark/dataset_v1.json
    latest_report_path: reports/benchmarks/latest.json
    baseline_run_id: "20260225T142209Z"
    generated_at_utc: "2026-02-25T14:22:21.258487Z"
    summary:
      total_queries: 6
      successful_queries: 6
      failed_queries: 0
      error_rate: 0.0
      citation_coverage: 1.0
      recall_at_k: 1.0
      keyword_hit_rate: 1.0
      mrr: 0.4166666666666667
    interpretation:
      - baseline_is_functional_but_ranking_quality_is_low_for_top1
      - deterministic_hash_embedding_is_non_semantic_placeholder
  p3_2_validation:
    run_id: "20260225T144807Z"
    report_path: reports/benchmarks/latest.json
    generated_at_utc: "2026-02-25T14:48:22Z"
    summary:
      total_queries: 6
      successful_queries: 6
      failed_queries: 0
      error_rate: 0.0
      citation_coverage: 1.0
      recall_at_k: 1.0
      keyword_hit_rate: 1.0
      mrr: 0.8333333333333334
    gate_check:
      min_mrr_required: 0.65
      min_mrr_passed: true
  gates:
    min_success_rate: 0.99
    min_citation_coverage: 1.0
    min_recall_at_k: 0.95
    min_mrr: 0.65

p0_p1_progress:
  p0_direction_lock: done
  p1_vertical_slice: done
  p2_hardening: done
  p3_1_benchmark: done
  p3_2_retrieval_real: done
  p3_3_enterprise_auth: done
  p3_4_cicd_discipline: done
  p4_0_ai_decision_trail: done
  p4_1_audit_query_export_signing: done
  p4_2_audit_export_gcs_and_advanced_filters: done
  p4_3_regulator_bundle_and_admin_cross_tenant: done
  p4_4_crypto_verify_and_regulator_package: done
  p5_governance_retention_immutability_connectors: done
  p6_retention_enforcement_engine: done

p4_audit_trail_engine:
  status: p4_4_done
  write_endpoint: POST /v1/decisions
  query_endpoint: POST /v1/decisions/query
  export_endpoint: POST /v1/decisions/export
  bundle_endpoint: POST /v1/decisions/bundle
  package_endpoint: POST /v1/decisions/package
  verify_endpoint: POST /v1/decisions/verify
  admin_query_endpoint: POST /v1/admin/decisions/query
  report_endpoint: GET /v1/decisions/{id}/report
  sql_tables:
    - ai_decisions
    - ai_decision_context_docs
    - ai_decision_context_chunks
    - retention_policies
    - legal_holds
    - audit_artifacts
  invariants:
    - idempotent_by_tenant_and_decision_id
    - decision_context_docs_must_exist_in_documents_table
    - optional_context_chunks_must_belong_to_context_docs
  query_capabilities:
    - decision_id_prefix_filter
    - decision_ids_filter
    - model_and_model_version_filters
    - outputs_filter
    - decision_trace_id_filter
    - text_filter_on_input_and_output
    - context_chunks_all_match_filter
    - confidence_range_filter
    - confidence_band_filter
    - created_at_range_filter
    - context_docs_all_match_filter
    - offset_limit_pagination
    - asc_desc_ordering
  admin_controls:
    - admin_cross_tenant_query_requires_jwt_and_admin_api_key
    - admin_query_accepts_tenants_list
  report_export:
    gcs_bucket_env: REPORTS_BUCKET
    object_prefix: reports/{tenant}/audit/
    hash_field: report_hash_sha256
    optional_signature:
      alg: hmac-sha256
      key_env: AUDIT_REPORT_SIGNING_KEY
      key_id_env: AUDIT_REPORT_SIGNING_KEY_ID
  regulator_bundle:
    object_prefix: reports/{tenant}/audit/bundles/
    supports_case_id_and_regulator_ref: true
    includes_per_decision_report_hashes: true
  regulator_package:
    object_prefix: reports/{tenant}/audit/packages/{package_id}/
    manifest_file: manifest.json
    evidence_files:
      - decision_reports/*.json
      - policy_snapshot.json (optional)
  cryptographic_verification:
    endpoint: POST /v1/decisions/verify
    verifies:
      - report_hash_sha256
      - signature_hmac_sha256
    default_tenant_path_guard: true

p5_governance_connectors:
  status: done
  connector_ingest:
    gcs_import_endpoint: POST /v1/connectors/gcs/import
    dedup_strategy: content_hash_unique_by_tenant
    writes_to_raw_prefix: raw/{tenant}/{doc_id}/
  retention_policy:
    upsert_endpoint: POST /v1/admin/retention-policies
    list_endpoint: GET /v1/admin/retention-policies
    defaults:
      artifact_type: audit_artifacts
      retain_days: 365
      legal_hold_enabled: true
      immutable_required: true
  legal_hold:
    create_endpoint: POST /v1/admin/legal-holds
    release_endpoint: POST /v1/admin/legal-holds/release
    list_endpoint: GET /v1/admin/legal-holds
    enforced_controls:
      - jwt_oidc_auth_required
      - x_admin_key_required
  artifact_immutability:
    write_mode: gcs_if_generation_match_0
    conflict_behavior: http_409
    registry_table: audit_artifacts

p6_retention_enforcement:
  status: done
  endpoint: POST /v1/admin/retention/enforce
  modes:
    - dry_run
    - delete
  candidate_filter:
    - tenant_optional
    - artifact_type_optional
    - deleted_at_is_null
  legal_hold_scope_mapping:
    - tenant
    - artifact
    - decision
    - document
    - case
  audit_artifact_soft_delete_fields:
    - deleted_at
    - deleted_by
    - deletion_reason
    - delete_job_id
  gcs_delete_strategy:
    generation_precondition_when_available: true
  authenticated_smoke:
    checked_at_utc: "2026-02-25T21:44:00Z"
    dry_run_http: 200
    dry_run_trace_id: "6ef64f51-fb5a-4539-b58a-9964bc4791e1"
    delete_http: 200
    delete_trace_id: "52698ca4-3e2c-4971-b0ce-e0bfcd8ee094"
    scanned: 3
    deleted: 0
    skipped_policy_missing: 3
  retention_policy_seed:
    applied_at_utc: "2026-02-25T21:47:00Z"
    tenant: default
    retain_days: 3650
    artifact_types:
      - decision_report
      - policy_snapshot
      - regulator_package_manifest
  post_seed_dry_run:
    checked_at_utc: "2026-02-25T21:48:00Z"
    http: 200
    trace_id: "882ce2d8-e8dc-4bf9-a596-60cb8b6ad525"
    scanned: 3
    skipped_not_expired: 3
    skipped_policy_missing: 0

p3_parallel_execution:
  p3_2_retrieval_real:
    status: done
    embedding_backend: vertex_text_embedding_with_dimension_projection
    target_embedding_dimensions: 128
    rollout_script: scripts/enable_vertex_backend.sh
    success_gate: benchmark.gates.min_mrr >= 0.65
    last_validation_run: "20260225T144807Z"
    latest_mrr: 0.8333333333333334
  p3_3_enterprise_auth:
    status: done
    mode: jwt_oidc_bearer_verification
    rollout_script: scripts/apply_p3_auth_oidc.sh
    pubsub_push_oidc_rollout_script: scripts/apply_p3_pubsub_push_oidc.sh
    issuer: https://alchimista.eu.auth0.com/
    audience: https://api.alchimista.ai
    tenant_claims:
      - https://alchimista.ai/tenant
      - tenant
      - tenants
    require_tenant_claim: true
    protected_endpoints:
      - ingestion-api-service: /v1/ingest /v1/ingest/complete /v1/doc/{id} /v1/admin/replay-dlq
      - rag-query-service: /v1/query
      - document-processor-service: /v1/process
    transitional_exceptions:
      - /v1/healthz
      - /v1/readyz
    pubsub_push_oidc:
      status: enforced
      subscription: doc-ingest-sub
      push_endpoint: https://document-processor-service-pe7qslbcvq-ez.a.run.app/v1/process/pubsub
      oidc_service_account: ingestion-api-sa@secure-electron-474908-k9.iam.gserviceaccount.com
      oidc_audience: https://document-processor-service-pe7qslbcvq-ez.a.run.app/v1/process/pubsub
      allow_unauthenticated_pubsub: false
    validation:
      checked_at_utc: "2026-02-25T19:47:28Z"
      readyz_ingestion_http: 200
      noauth_rag_query_http: 401
      noauth_ingestion_doc_http: 401
      benchmark_gate_run_id_after_pubsub_oidc: "22413130015"
      benchmark_gate_status_after_pubsub_oidc: success
  p3_4_cicd_discipline:
    status: done
    workflows:
      - .github/workflows/ci.yml
      - .github/workflows/benchmark-gate.yml
      - .github/workflows/deploy-cloud-run.yml
      - .github/workflows/rotate-audit-signing-key.yml
    deploy_script: scripts/deploy_cloud_run_service.sh
    benchmark_gate_script: scripts/check_benchmark_gate.py
    github_environment: test
    required_environment_secrets:
      - GCP_WORKLOAD_IDENTITY_PROVIDER
      - GCP_DEPLOY_SERVICE_ACCOUNT
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
    deploy_service_account_requirements:
      project_roles:
        - roles/run.admin
        - roles/cloudbuild.builds.editor
        - roles/artifactregistry.reader
        - roles/serviceusage.serviceUsageConsumer
        - roles/storage.objectAdmin
      secret_level_roles:
        - secret: alchimista-audit-report-signing-key
          role: roles/secretmanager.secretVersionAdder
      service_account_user_on:
        - ingestion-api-sa@secure-electron-474908-k9.iam.gserviceaccount.com
        - document-processor-sa@secure-electron-474908-k9.iam.gserviceaccount.com
        - rag-query-sa@secure-electron-474908-k9.iam.gserviceaccount.com
        - 994021588311-compute@developer.gserviceaccount.com

security_hardening:
  dedicated_service_accounts_enabled: true
  core_services_using_default_compute_sa: false
  db_credentials_in_secret_manager: true
  buckets_cmek_ubla_enforced: true
  signed_url_runtime_signing_mode: iam_signblob_via_access_token
  aiplatform_user_role_bound_to_processor_and_rag: true
  dlq_replay_admin_key_configured: true
  dlq_replay_admin_key_source: secret_manager:alchimista-admin-api-key
  audit_report_signing_key_rotation:
    script: scripts/rotate_audit_report_signing_key_secret.sh
    workflow: .github/workflows/rotate-audit-signing-key.yml
    cadence: monthly_or_manual
  processor_backpressure_guard_enabled: true

observability:
  dashboard:
    name: projects/994021588311/dashboards/b595714b-b0ab-4534-ac90-d39c9373f5e3
    display_name: Alchimista P2 Operations
  alert_policies_active:
    - name: projects/secure-electron-474908-k9/alertPolicies/8840730067332886076
      display_name: Alchimista P2 Ingest Backlog Age
    - name: projects/secure-electron-474908-k9/alertPolicies/9829802951063327188
      display_name: Alchimista P2 DLQ Growth
    - name: projects/secure-electron-474908-k9/alertPolicies/17998058155877203706
      display_name: Alchimista P2 Processor P95 Latency
    - name: projects/secure-electron-474908-k9/alertPolicies/883252886433335131
      display_name: Alchimista P2 Cloud SQL Connections
  legacy_policies_disabled:
    - name: projects/secure-electron-474908-k9/alertPolicies/13114588826634431855
      display_name: Pub/Sub Undelivered Messages
    - name: projects/secure-electron-474908-k9/alertPolicies/431833831792684197
      display_name: Cloud Run P95 Latency High

validation:
  last_smoke_test_at: "2026-02-25T14:06:31Z"
  smoke_test_result: passed
  sample_doc_id: d4f5b676-e92d-4def-9d75-82e1f454f922
  sample_trace_id: 9a4de16c-5169-4afc-bb8b-0f551172e1a1
  ingest_subscription_push_endpoint: https://document-processor-service-pe7qslbcvq-ez.a.run.app/v1/process/pubsub
  runtime_vector_backend_active: vertex_ai_vector_search
  processor_runtime_limits:
    max_instances: 4
    concurrency: 4
    timeout_seconds: 900
    max_inflight: 8
  rag_runtime_limits:
    max_instances: 8
    concurrency: 40
  ingestion_runtime_limits:
    max_instances: 10
    concurrency: 80
  pubsub_retry_budget:
    ack_deadline_seconds: 60
    min_retry_delay: 10s
    max_retry_delay: 300s
    max_delivery_attempts: 5
  dlq_replay_test:
    trace_id: 40196d12-850a-4884-b456-40c97b29acf2
    requested: 1
    pulled: 0
    replayed: 0
  structured_logging_validation:
    ingestion_trace_id: 9e9b3270-b594-4bda-b17b-b2de0686ce07
    ingestion_job_id: a43546bc-53fc-45dc-8339-ed5396c62dfb
    processor_trace_id: 9a4de16c-5169-4afc-bb8b-0f551172e1a1
    processor_job_id: 4615523b-7095-445f-82d9-f432bff5759f
    rag_trace_id: 9a4de16c-5169-4afc-bb8b-0f551172e1a1
    rag_job_id: rag-query:9a4de16c-5169-4afc-bb8b-0f551172e1a1
